spring.application.name=Dummy
server.port=8067

server.servlet.context-path=/app
spring.datasource.url=jdbc:mysql://localhost:3306/dummy
spring.datasource.username=root
#personal db password----------
#spring.datasource.password=Ashish@2003


#office db password
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto = update

razorpay.key.id=rzp_test_T0CLhszzwRpcqW  
razorpay.key.secret=lFU2AWETB9VDs4e0q28XKURQ
spring.security.user.name=Admin
spring.security.user.password=5432